import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../../providers/auth-providers";
import QueryProvider from "../../providers/query-provider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <QueryProvider>
          <AuthProvider>{children}</AuthProvider>
          <ReactQueryDevtools/>
        </QueryProvider>
      </body>
    </html>
  );
}
